### ISSUE TITLE
Packing Checklist Additions

### ISSUE THREAD

**Issue by bobvilliam** [Mines-Rocketry-Club/org-central#7]
Changes / Additions

- K570 & L285 (once motor box is taken off)
- 2x J290 P38
- Cesaroni 5G casing
- Big ignitors
- Aluminum Tape
- A23 Batteries
- A23 Battery Holders
- FAR Higher Lower Stage
- FAR Higher Upper Stage
- 12 inch parachute
- 24-26 inch parachute
- 36 inch parachute
- 48 inch parachute
- Quick links / shock cord box

**Comment by bobvilliam** [comment]
And a crap ton of rubber bands
So many rubber bands

**Comment by tpowell11** [comment]
[0744e23](https://github.com/Mines-Rocketry-Club/org-central/commit/0744e23f23ed4e388a51c75e1b0d0f2e5cceecaf) added items. parachutes compressed to single subset item
